<%-- 
    Document   : init
    Created on : Nov 10, 2011, 8:59:26 PM
    Author     : FreeX
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Bảo mật</h1>
    </body>
</html>
