$(document).ready(function(){
$(".flip").click(function(){
    $(".panel").slideToggle("slow");
  });

  $(".flip1").click(function(){
    $(".panel1").slideToggle("slow");
  });
  
  $(".flip2").click(function(){
    $(".panel2").slideToggle("slow");
  });
  
  $(".flip3").click(function(){
    $(".panel3").slideToggle("slow");
  });
  $(".flip4").click(function(){
    $(".panel4").slideToggle("slow");
  });
  
  $(".flip5").click(function(){
    $(".panel5").slideToggle("slow");
  });
  
  $(".flipTop").click(function(){
    $(".panelTop").slideToggle("slow");
  });
  
});



